# Site settings
title: "littlemap"
email: me@edisonorellana.com
description: "Follow my projects"
baseurl: "/littlemap"
url: "littlemap.me"
title_description: "Geographic Information Science graduate from the University of Illinois at Urbana Champaign"
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: ""
disqus_account: edisondotme
github_repository: https://github.com/jacobtomlinson/
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: edisondotme
github_username:  edisondotme
linkedin_link: www.linkedin.com/in/edisondotme 

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
